### ISSUE TITLE
Show power status (on/off)

### ISSUE THREAD

**Issue by wopfel** [Napsty/check_shelly#3]
Hi,
I'm interested in the status of the device in the output, whether it is on, or off.

Output from Shelly device:
`{"id": 1, "src": "shellyplus1pm-xxx", "result": {"id": 0, "source": "WS_in", "output": true, "apower": 0.0, "voltage": 230.5, "current": 0.0, ...`

The status is shown in the `output` field.

I've changed the check script. The power status is printed now.

Example output (SWITCH_0 is on):

`SHELLY OK: Device (shellyplus1pm-xxx) SWITCH_0 is on, currently using 0 Watt / 0 Amp |power=0 current=0 total_power=50.982 temp=46.2 powerstatus=1`

If you're interested in this, I'll be happy to create a PR or just share my changes right here.

Regards,
Bernd

**Comment by Napsty** [comment]
Hi @wopfel 
Yes, a PR would be appreciated. I had to remove my Shelly from the power cabinet and I cannot test locally anymore.
We could also combine the on/off situation with the request #2 .

**Comment by wopfel** [comment]
I think I'll take care of #2, since I'm also interested checking for on/off state.
